# Start of Selection
# frozen_string_literal: true

source "https://rubygems.org"

gemspec

gem "pry"
gem "rake"

# Spec
gem "rspec", "~> 3.0"

# Linter
gem "rubocop", "~> 1.21"
gem "rubocop-rake"
gem "rubocop-rspec", require: false

# Dev management
gem "bundler-audit", "~> 0.9.2"
gem "fasterer", "~> 0.11.0"
gem "overcommit"

# Types
gem "sorbet"
gem "sorbet-runtime"
gem "tapioca"
